services:
  backend:
    build: .
    container_name: Trimora-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
      - ./output:/app/output
    environment:
      - MAX_CONCURRENT_JOBS=5
    restart: unless-stopped

  frontend:
    build: ./dashboard
    container_name: Trimora-frontend
    ports:
      - "5175:5173"
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - backend
